#define ENABLE_EXTENSION_AFFINITY
#define ENABLE_EXTENSION_DEBUG
#define ENABLE_EXTENSION_LABELING
#define ENABLE_EXTENSION_CHANNEL_EVT
#define ENABLE_EXTENSION_PARAMS_EVT
#define ENABLE_EXTENSION_COUNTED_EVT
#define ENABLE_EXTENSION_RTITF
#define ENABLE_EXTENSION_CALL_SITES
